### ISSUE TITLE
Items are renamed to the chosen language

### ISSUE THREAD

**Issue by LordRazen** [LordRazen/leather-colorizer#27]
![grafik](https://user-images.githubusercontent.com/9381368/150676558-bf2e6d68-ad90-4319-94e4-571a34c7118e.png)

**Comment by LordRazen** [comment]
Fixed Problem with translation and missing "(+3 Armor)" Info

**Comment by bmack94** [comment]
solved with https://github.com/LordRazen/leather-colorizer/pull/26
