### ISSUE TITLE
mission artifact

### ISSUE THREAD

**Issue by seema84** [LordRazen/leather-colorizer#40]
Failed to execute goal on project Leather-Colorizer: Could not resolve dependencies for project com.minecraftheads:Leather-Colorizer:jar:1.1: Could not find artifact com.minecraftheads:plugin-utils:jar:1.6-SNAPSHOT in spigotmc-repo (https://hub.spigotmc.org/nexus/content/repositories/snapshots/)

**Comment by bmack94** [comment]
Hi @seema84 , we have not pushed the jar into any maven repo yet.
To use it you have to install https://github.com/LordRazen/plugin-utils into your local .m2 repo. (check the docs)
Then it can be used by maven to build this artifact.

If you have further questions or the issue persists please reopen the issue.

Regards, bmack

**Comment by seema84** [comment]
thanks for the response

**Comment by solonovamax** [comment]
@seema84
The plugin is currently also in the process of being rewritten, so whenever that is finished, all the artifacts it depends on will be available (& prebuilt binaries will be provided)

**Comment by seema84** [comment]
@solonovamax
Then I'm excited to see it published. Thanks for the information.
