### ISSUE TITLE
Cleaned Leather Amor cannot be dyed again

### ISSUE THREAD

**Issue by LordRazen** [LordRazen/leather-colorizer#42]
Kleiner Interessanter Bugreport: Wenn man eine Lederrüstung die bereits gefärbt ist in einem Kessel entfärbt, kann man sie nicht beim Lederfärber umfärben, die Rüstung hat 2 Tags auf sich, normale gecraftete haben nur einen Tag. Wenn man dann hingeht und die Lederrüstung einmal in einen Armorstand reinpackt, das Inventar schließt und wieder in den Armorstand geht, hat die Rüstung nur noch einen Tag und kann über den Lederfärber gefärbt werden.

**Comment by bmack94** [comment]
I cannot reproduce this bug in 1.3
