### ISSUE TITLE
Fix the /lc command

### ISSUE THREAD

**Issue by LordRazen** [LordRazen/leather-colorizer#49]
![grafik](https://github.com/user-attachments/assets/64dca410-07d4-4b07-b367-2089ef40ab7a)

The command should work properly with /leathercolorizer and the alias /lc, 
not something like this: `/leathercolorizer:/leathercolorizer`

**Comment by bmack94** [comment]
Afaik its not possible to disable the plugin command prefix.

**Comment by LordRazen** [comment]
![grafik](https://github.com/user-attachments/assets/d5377ab2-1d46-4669-8a9b-52b359a7d5fa)
Normal command behaviour...
